import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('offers a custom Windows stress command with explicit staged duration and unit controls', async () => {
  const source = await readFile(new URL('./WindowsStress.vue', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /<b>自定义压测命令<\/b>/)
  assert.match(source, /v-model="customMode"/)
  assert.match(source, /v-model="customDurationHours"/)
  assert.match(source, /v-model="customDurationMinutes"/)
  assert.match(source, /aria-label="压测时长（小时）"/)
  assert.match(source, /aria-label="压测时长（分钟）"/)
  assert.match(source, /\{\{ customPreset\.title \}\}/)
  assert.match(source, /整机 \$\{duration\} 测试/)
  assert.match(source, /GPU、CPU\/内存、磁盘各运行/)
  assert.match(source, /采样间隔 \$\{interval\} 秒/)
  assert.match(source, /normalizeCustomDurationParts/)
  assert.match(source, /const hours = Math\.floor\(minutes \/ 60\)/)
  assert.match(source, /class="custom-command-config command-config-stack"/)
  assert.match(source, /class="command-config-stack"/)
  assert.match(source, /补测模块/)
  assert.match(source, /\.command-config-row \.custom-command-label \{ flex: 0 0 78px;/)
  assert.match(source, /<b>常规压测<\/b>/)
  assert.match(source, /按所选模块执行一轮完整压测。/)
  assert.match(source, /class="duration-input-group"/)
  assert.match(source, /\.command-panel \.preset-content \{ display: flex; flex-direction: column;/)
  assert.match(source, /\.command-panel > \.el-button \{ position: absolute; top: 16px; right: 16px;/)
  assert.match(source, /\.command-panel \.preset-content > pre \{ margin-top: auto;/)
  assert.match(source, /\.supplement-report-dir \{ width: 100%; margin: 0 0 24px;/)
  assert.match(source, /class="command-panels"/)
  assert.match(source, /class="operation-card windows-section"/)
  assert.doesNotMatch(source, /custom-command-card/)
  assert.doesNotMatch(source, /presetGroups/)
  assert.doesNotMatch(source, /整机 36 小时正式压测/)
  assert.match(source, /<article class="preset-card command-panel">/)
  assert.match(source, /customPreset\.command/)
  assert.match(source, /补测命令/)
  assert.match(source, /supplementReportDir/)
  assert.match(source, /aria-label="原始报告目录" style="width: 100%"/)
  assert.doesNotMatch(source, /请先填写原始压测报告文件夹/)
  assert.doesNotMatch(source, /填写原始报告目录后生成补测命令/)
  assert.match(source, /<pre>\{\{ supplementPreset\.command \}\}<\/pre>/)
  assert.match(source, /supplementDiskScope/)
  assert.match(source, /supplementDriveOptions/)
  assert.match(source, /v-model="supplementDrives"/)
  assert.match(source, /supplementDurationHours/)
  assert.match(source, /supplementDurationMinutes/)
  assert.ok(source.indexOf('v-model="supplementMode"') < source.indexOf('class="supplement-report-dir"'))
  assert.ok(source.indexOf('class="supplement-duration"') < source.indexOf('class="supplement-report-dir"'))
  assert.match(source, /const supplementMode = ref<'gpu' \| 'cpu' \| 'disk'>\('gpu'\)/)
  assert.match(source, /MergeBaseReportDir/)
  assert.match(source, /磁盘补测范围/)
  assert.match(source, /el-radio v-model="supplementDiskScope"/)
  assert.doesNotMatch(source, /<el-radio-group v-if="supplementMode === 'disk'" v-model="supplementDiskScope"/)
})
